FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build

ENV StressRunDuration=0
ARG DEBIAN_FRONTEND=noninteractive

# Setup for nodejs
RUN curl -sL https://deb.nodesource.com/setup_16.x | bash -

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    libunwind-dev \
    nodejs \
    git

ARG gitBranch=prkrishn/aot-tests

WORKDIR /src
ADD https://api.github.com/repos/dotnet/aspnetcore/git/ref/heads/${gitBranch} /aspnetcore.commit

RUN git init \
    && git fetch https://github.com/aspnet/aspnetcore ${gitBranch} \
    && git reset --hard FETCH_HEAD \
    && git submodule update --init \
    && git remote add origin https://github.com/aspnet/aspnetcore

RUN ./restore.sh
RUN .dotnet/dotnet publish -c Release --no-restore -o /out/app ./src/Components/benchmarkapps/Wasm.Performance/Driver/Wasm.Performance.Driver.csproj
RUN chmod +x /out/app/Wasm.Performance.Driver

RUN .dotnet/dotnet workload install wasm-tools
RUN .dotnet/dotnet publish -c Release -o /out/aot-app ./src/Components/benchmarkapps/Wasm.Performance/Driver/Wasm.Performance.Driver.csproj /p:RunAOTCompilation=true
RUN chmod +x /out/aot-app/Wasm.Performance.Driver

WORKDIR /out/
FROM selenium/standalone-chrome:latest as final

COPY --from=build ./out ./out
COPY ./exec.sh ./

ENTRYPOINT [ "bash", "./exec.sh" ]
